version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  app:
    build: ./docker/fastapi
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./app:/app
