version: '3'

dotenv:
  - ".env"

vars:
  PROJECT_NAME: rag-chatbot
  DOCKER_COMPOSE_FILE: docker-compose.yml

tasks:

  install:
    desc: "Build Docker images"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up --build -d
      - docker exec -it ollama ollama run $OLLAMA_LLM
      - docker exec -it ollama ollama pull $OLLAMA_EMBEDDINGS_MODEL
      - docker exec -it fastapi python vector_store.py # 埋め込み

  up:
    desc: "Start the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up -d

  stop:
    desc: "Stop the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} stop
  
  down:
    desc: "Down the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down
