version: '3'

vars:
  PROJECT_NAME: rag-chatbot
  DOCKER_COMPOSE_FILE: docker-compose.yml

tasks:
  dev:
    desc: "Start FastAPI in local development mode"
    cmds:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  install:
    desc: "Build Docker images"
    cmds:
      - if [ ! -f .env ]; then cp .env.example .env; fi
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up --build -d

  up:
    desc: "Start the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up -d

  stop:
    desc: "Stop the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} stop
  
  down:
    desc: "Down the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down

  clean:
    desc: "Remove Docker containers, volumes, and images"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down -v
      - docker system prune -af

  logs:
    desc: "Show logs for FastAPI container"
    cmds:
      - docker logs -f {{.PROJECT_NAME}}_app_1
