version: '3'

vars:
  PROJECT_NAME: rag-chatbot
  DOCKER_COMPOSE_FILE: docker-compose.yml

tasks:

  install:
    desc: "Build Docker images"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up --build -d
      - docker exec -it ollama ollama run phi3:3.8b-mini-4k-instruct-q5_K_M
      - docker exec -it ollama ollama pull mxbai-embed-large

  up:
    desc: "Start the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up -d

  stop:
    desc: "Stop the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} stop
  
  down:
    desc: "Down the Docker containers"
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down
